name: Chumkin
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4
  flutter_launcher_name: ^0.0.1
  google_sign_in: ^4.2.0
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.5
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+2
  geolocator: ^5.3.0
  flutter_svg: ^0.17.3+1
  cached_network_image: ^2.0.0
  image_picker: ^0.6.4
  path_provider: ^1.6.5
  uuid: ^2.0.4
  animator: ^1.0.0+5
  timeago: ^2.0.26
  image: ^2.1.4
  firebase_messaging: ^6.0.13
  # cached_network_image: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/icon.png" 
  android: true
  ios: true

flutter_launcher_name:
  name: "Chumkin"

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg


  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Pattaya
      fonts:
       - asset: assets/fonts/Pattaya-Regular.ttf
         weight: 400
         style: italic 